# Generated by Django 4.2.8 on 2026-01-13 05:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Responsibility',
                'verbose_name_plural': 'Responsibilities',
                'ordering': ['-priority', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='ResponsibilityCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3498db', max_length=7)),
            ],
            options={
                'verbose_name': 'Responsibility Category',
                'verbose_name_plural': 'Responsibility Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResponsibilityRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_type', models.CharField(choices=[('led', 'Led'), ('arranged', 'Arranged'), ('contributed', 'Contributed'), ('supported', 'Supported')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsibility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='responsibilities.responsibility')),
            ],
            options={
                'verbose_name': 'Responsibility Role',
                'verbose_name_plural': 'Responsibility Roles',
            },
        ),
    ]
