# Generated by Django 4.2.8 on 2026-01-13 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('responsibilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='responsibilityrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responsibility',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigned_responsibilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responsibility',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsibilities', to='responsibilities.responsibilitycategory'),
        ),
        migrations.AddField(
            model_name='responsibility',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_responsibilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='responsibilityrole',
            unique_together={('responsibility', 'user', 'role_type')},
        ),
        migrations.AddIndex(
            model_name='responsibility',
            index=models.Index(fields=['status'], name='responsibil_status_a4a937_idx'),
        ),
        migrations.AddIndex(
            model_name='responsibility',
            index=models.Index(fields=['priority'], name='responsibil_priorit_295866_idx'),
        ),
        migrations.AddIndex(
            model_name='responsibility',
            index=models.Index(fields=['due_date'], name='responsibil_due_dat_b43428_idx'),
        ),
    ]
