# Generated by Django 4.2.8 on 2026-01-13 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timeline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='timeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='timeline.timeline'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_timelines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['timeline', 'event_date'], name='timeline_ti_timelin_3d4179_idx'),
        ),
        migrations.AddIndex(
            model_name='timeline',
            index=models.Index(fields=['category'], name='timeline_ti_categor_652f64_idx'),
        ),
        migrations.AddIndex(
            model_name='timeline',
            index=models.Index(fields=['is_published'], name='timeline_ti_is_publ_60c585_idx'),
        ),
    ]
